language: android
dist: trusty

notifications:
  slack:
    rooms:
      - supla:dauFpwhgEGeyy9ERzqOYeJyY#github

android:
  components:
    - build-tools-29.0.3
    - android-29
    - extra
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
